Lesson9
DOOMSID/game_flutter pull request #3
Opened 2023-11-15 16:31 UTC by DOOMSID

add new files and start_screen for my App

2023-11-16 22:58 UTC, VadymPinchuk requested changes
деякого порядку треба навести. але взагалі молодець )

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +  // ignore: library_private_types_in_public_api
це не потрібно

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +  _MovingImagesWidgetState createState() => _MovingImagesWidgetState();
State<MovingImagesWidget> createState() =>

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +
форматування відсутнє. А потрібно щоб було )
dart format lib/

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +  Widget buildAnimatedImage(double initialTop, double initialLeft, double initialRight, double directionMultiplierHorizontal, double directionMultiplierVertical, String imagePath, double widthImage,
у таких довгих функціях краще ставити кому після останнього аргумента - і форматувати. тоді код буде більш читабельний

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +          final horizontalOffset = directionMultiplierHorizontal * curvedAnimation.value * (MediaQuery.of(context).size.width - MediaQuery.of(context).padding.left);
var padding = MediaQuery.paddingOf(context) можна винести в локальну змінну в методі білд. і використати скрізь

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +          final verticalOffset = (directionMultiplierVertical - curvedAnimation.value) * (MediaQuery.of(context).size.height - MediaQuery.of(context).viewPadding.top);
var size = MediaQuery.sizeOf(context) можна винести в локальну змінну в методі білд. і використати скрізь

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +          ),
dart format /lib/
потрібно все форматувати.

2023-11-16 22:58 UTC, VadymPinchuk commented on lib/start_screen.dart
> +        buildAnimatedImage(-3 * mediaQuery.viewPadding.top - kToolbarHeight, 0, 0, -0.5, 1.0, 'assets/images/flower1.png', mediaQuery.size.width, mediaQuery.size.width),
ось тут також багато безладу. став кому після  останнього аргументу будь ласка

2023-11-17 18:26 UTC, DOOMSID commented
add start_screen

2023-11-17 18:26 UTC, merged